### ISSUE TITLE
Select checkbox with Enter

### ISSUE THREAD

**Issue by wisniewski94** [wisniewski94/Keyboard-UI#9]
Add hit ENTER key to select checkbox feature.

**Comment by vijaykrishna536** [comment]
@wisniewski94 Correct me If I'm wrong is this feature to be included
from scratch or we have to make changes to an existing code?
If the later one is true then can you tell me exactly where in the 
project structure those files exist

**Comment by wisniewski94** [comment]
@vijaykrishna536 I'm sorry for the mess in project structure, I will clean this up later this day.

Source js and sass files are inside src folder. Dist is used by npm users. /js is a garbage right now or its being used by /test (as I said I need to clean this up)

If you have an idea how to solve this issue then you should focus on src directory and gulp tasks ```gulp watch``` and ```gulp build```. All js should be inside ```./src/keyui.js```

Use vanilla JS. ES6 allowed ;)


Thank you for your interest in this :)    

EDIT: I'm talking about develop branch

**Comment by wisniewski94** [comment]
Done, updated ```README.MD``` a bit aswell.

**Comment by Shivam2498** [comment]
If you can explain what to do, can I take this?

**Comment by wisniewski94** [comment]
Sure, when checkbox is focused, when you press enter button it should get checked but form shouodn't be submited

**Comment by wisniewski94** [comment]
Meh, missclick, I will reopen this issue later
